# Generated by Django 3.0.8 on 2021-02-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=50)),
                ('dlink', models.CharField(max_length=2000)),
            ],
        ),
    ]
