# Generated by Django 3.0.8 on 2021-02-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='dlink',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apk',
            name='imgurl',
            field=models.CharField(max_length=100000),
        ),
    ]
