# Generated by Django 3.0.8 on 2021-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210218_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='imgurl',
            field=models.CharField(max_length=10000),
        ),
    ]
