# Generated by Django 3.0.8 on 2021-02-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210218_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='apk',
            name='type',
            field=models.CharField(default='game', max_length=50),
        ),
    ]
